/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package alysson.cirilo.resume.cli

import alysson.cirilo.resume.drivers.latexsober.makeLatexSoberDriver

fun main() {
    val resume = makeResume()
    val toString = makeLatexSoberDriver().convert(resume)
    print(toString)
}

