/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("alysson.cirilo.resume.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")

    implementation(projects.utilities)
    implementation(projects.drivers.latexSober)
}

application {
    // Define the main class for the application.
    mainClass.set("alysson.cirilo.resume.app.AppKt")
}
