/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("alysson.cirilo.resume.kotlin-application-conventions")
}

dependencies {
    implementation(projects.drivers.latexSober)
    implementation(projects.drivers.latexAwesome)
}

application {
    // Define the main class for the application.
    mainClass.set("alysson.cirilo.resume.app.AppKt")
}
