/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package alysson.cirilo.resume.app

import alysson.cirilo.resume.drivers.LatexSoberResumeDriver

fun main() {
    val resume = makeResume()
    val toString = LatexSoberResumeDriver().convert(resume)
    print(toString)
}

