/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package alysson.cirilo.resume.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
