/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("alysson.cirilo.resume.kotlin-library-conventions")
}

dependencies {

    testImplementation("com.google.truth:truth:1.1.3")
}
