name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: build 🛠️ 
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6

      - name: ☕ Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'adopt'

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: 🔨 Build Project
        working-directory: make-resume
        run: ./gradlew build --console=colored

      - name: 📝 Make resumes
        run: make markupfiles IS_CI=true

      - name: 📤 Upload resumes markup
        uses: actions/upload-artifact@v7
        with:
          name: resumes-markup
          path: build
          retention-days: 1

  compile-resumes:
    name: compile resumes 📜
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6

      - name: 📦 Install poppler-utils
        run: apt update && apt install -y poppler-utils

      - name: ⏳ Wait for markup files
        uses: yogeshlonkar/wait-for-jobs@v0
        with:
          jobs: 'build 🛠️'
          interval: '2500'
          ttl: '5'

      - name: 📥 Download resumes markup
        uses: actions/download-artifact@v8
        with:
          name: resumes-markup
          path: build

      - name: 📝 Make resumes & previews
        run: make all IS_CI=true SHORT_CIRCUIT=true

      - name: 📤 Upload resumes & previews
        uses: actions/upload-artifact@v7
        with:
          name: resumes
          path: build/output
          retention-days: 1

  deploy:
    name: deploy 🚀
    needs: [compile-resumes]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6

      - name: 📥 Download resumes
        uses: actions/download-artifact@v8
        with:
          name: resumes
          path: build/output

      - name: 🚀 Upload resumes to orphan branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/output
          branch: resumes

      - name: 🚀 Deploy release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/output/alysson-cirilo-fancy-resume.pdf
            build/output/alysson-cirilo-sober-resume.pdf
            build/output/alysson-cirilo-markdown-resume.md
          body: |
            You can choose between the following resume flavors:
            * `alysson-cirilo-fancy-resume.pdf` if you want a modern and colored resume.
            * `alysson-cirilo-sober-resume.pdf` if you want a classic sober resume.
            * `alysson-cirilo-markdown-resume.md` if you want a resume in markdown format.
          
